# Generated by Django 4.2.6 on 2023-12-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddUser",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                (
                    "email",
                    models.EmailField(max_length=50, primary_key=True, serialize=False),
                ),
                ("message", models.CharField(max_length=300)),
            ],
        ),
    ]
