# Generated by Django 4.2.6 on 2023-12-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_addblog_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="addblog",
            name="category",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
    ]
